DROP TABLE PHONE;

DROP SEQUENCE SEQ_NO;

--테이블 생성 사용자이름, 나이, 주소, 전화번호
CREATE TABLE PHONE(
    USERNO NUMBER PRIMARY KEY,
    USERNAME VARCHAR2(20)NOT NULL,
    AGE NUMBER NOT NULL,
    ADDRESS VARCHAR2(100)NOT NULL,
    PHONE VARCHAR2(13) NOT NULL 
    );
    
SELECT * FROM PHONE;

--시퀀스 생성
CREATE SEQUENCE SEQ_NO
NOCACHE;

SELECT * FROM USER_SEQUENCES;

SELECT SEQ_NO.NEXTVAL FROM DUAL;

COMMENT ON COLUMN PHONE.USERNO IS'전화번호 순서';
COMMENT ON COLUMN PHONE.USERNAME IS'사용자 이름';
COMMENT ON COLUMN PHONE.AGE IS'사용자 나이';
COMMENT ON COLUMN PHONE.ADDRESS IS'사용자 주소';
COMMENT ON COLUMN PHONE.PHONE IS'전화번호';

INSERT INTO PHONE VALUES(SEQ_NO.NEXTVAL,'차은우',25,'강남','010-1234-1234');
INSERT INTO PHONE VALUES(SEQ_NO.NEXTVAL,'주지훈',26,'잠실','010-4158-1235');

--DELETE FROM PHONE WHERE USERNAME = '차은우';
    
commit;
