--DROP TABLE PRODUCT;

CREATE TABLE PRODUCT(
    PRODUCT_ID VARCHAR2(20)PRIMARY KEY,
    P_NAME VARCHAR2(15)NOT NULL,
    PRICE NUMBER NOT NULL,
    DESCRIPTION VARCHAR2(50),
    STOCK NUMBER NOT NULL
);

SELECT * FROM product;

INSERT INTO PRODUCT VALUES('nb_ss7','»ï¼º³ëÆ®ºÏ',1570000,'½Ã¸®Áî7',10);
INSERT INTO PRODUCT VALUES('nb_ama4','¸ÆºÏ¿¡¾î',1200000,'xcode4',20);
INSERT INTO PRODUCT VALUES('nb_ibm','ibmPC',750000,'window8',5);

COMMIT;


SELECT * FROM PRODUCT WHERE P_NAME LIKE '%»ï%';

--UPDATE PRODUCT SET PRODUCT_ID = ?, P_NAME = ?,PRICE = ?,DESCRIPTION =?, STOCK=?
INSERT INTO PRODUCT VALUES('df','adf','152','adf',2);